### ISSUE TITLE
Don't use default mappings

### ISSUE THREAD

**Issue by rosshadden** [rafaqz/ranger.vim#1]
Including with default mappings is an anti-pattern for vim plugins.  A better (and easy) pattern is to not ship with any, but suggest some in the readme.  This is a well-accepted and well-mannered pattern.

**Comment by rafaqz** [comment]
Sure... here on github a pull request is the well-mannered thing to do ;)

**Comment by rawsp33d** [comment]
Haha fair enough! :dog:

**Comment by rafaqz** [comment]
Mappings are now suggested in the readme.
