### ISSUE TITLE
Conflict with NERDTree

### ISSUE THREAD

**Issue by sh78** [rafaqz/ranger.vim#13]
NVIM v0.2.2, fish shell, macOS 10.13.4. Relevant lines of [vimrc](https://github.com/sh78/dotfiles/blob/af08cfabcce20dbdf5e875aed39491eaa85399e7/.vimrc#L502):

```
:nnoremap <Leader>t :NERDTreeToggle<CR>
:nnoremap <Leader>T :NERDTreeFind<CR>
" show hidden files in nerdtree
let NERDTreeShowHidden=1
" auto delete buffer of deleted files
let NERDTreeAutoDeleteBuffer = 1
" look nice
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
" ...
"" ranger.vim
map <leader>rr :RangerEdit<cr>
map <leader>rv :RangerVSplit<cr>
map <leader>rs :RangerSplit<cr>
map <leader>rt :RangerTab<cr>
map <leader>ri :RangerInsert<cr>
map <leader>ra :RangerAppend<cr>
map <leader>rc :set operatorfunc=RangerChangeOperator<cr>g@
```

On calling `:RangerEdit`, I get the following error:

```
NERD_tree_1                                                                                               0,0-1          All
NERDTree: 1 file(s) could not be loaded into the NERD tree
Error detected while processing function <SNR>85_RangerMagic[15]..<SNR>85_RangerNVim:
line   15:
Can only call this function in an unmodified buffer
Can only call this function in an unmodified buffer
Press ENTER or type command to continue
```
<img width="869" alt="2018-05-21 at 14 57 57" src="https://user-images.githubusercontent.com/1066135/40332153-e14b345a-5d07-11e8-8ead-996434dfb1fd.png">

After hitting Enter, I'm taken to a fullscreen NERDTree buffer:
<img width="365" alt="2018-05-21 at 14 58 15" src="https://user-images.githubusercontent.com/1066135/40332215-18415d0e-5d08-11e8-81d5-d862dbfe5476.png">

Can confirm that uninstalling NERDTree and restarting vim resolves the issue, allowing the ranger awesomeness to ensue.

I'm probably going to end up ditching NERDTree anyway, but just a heads up.

**Comment by rafaqz** [comment]
RangerEdit just opens the regular vim file explorer, which is then overridden by Ranger. Maybe NERD tree also overrides :e. I don't think its reconcilable, you just need to choose one.

**Comment by sh78** [comment]
Ok, thanks for looking into it!
