### ISSUE TITLE
Use ranger to change current working directory

### ISSUE THREAD

**Issue by mauroporras** [rafaqz/ranger.vim#19]
It'd be cool if we could use ranger to do both `:cd` and `:lcd`.

Thanks.

**Comment by rafaqz** [comment]
That should allready work using RangerCD or RangerLCD

**Comment by mauroporras** [comment]
That's so cool. I didn't see it documented. Thank you.

**Comment by rafaqz** [comment]
Oops it isn't! good catch. Do you want to put it in the readme with a suggested key mapping? I don't actually use it

**Comment by mauroporras** [comment]
@rafaqz Sure thing, will do.
