### ISSUE TITLE
BUG: Home and End keys stopped working

### ISSUE THREAD

**Issue by Zeioth** [rafaqz/ranger.vim#29]
The keys stopped working after installing this plugin. After user [this other plugin](https://github.com/francoiscabrol/ranger.vim) instead they work fine. Do this plugin automatically set remaps? If so, I would let the other add them themselves instead of pre-define them.

**Comment by rafaqz** [comment]
There are no key maps. You have to do it manually.

So test your problem with a clean Vim configuration. Isolate what is causing the problem. Probably its your setup. If not, report your findings here.
