### ISSUE TITLE
Command not found: `sed'  [Process exited 0]

### ISSUE THREAD

**Issue by mauroporras** [rafaqz/ranger.vim#3]
Always, after any file is selected, it's throwing:

```
Command not found: `sed'

[Process exited 0]
```

I do have sed installed:

```
➜  ~ which -a sed
/usr/local/bin/sed
/usr/bin/sed
```

**Comment by rafaqz** [comment]
This plugin doesn't use sed... that would be a pretty wild move on my part. But maybe ranger or vim does in the background? Or maybe one of your other plugins conflicts?

**Comment by rafaqz** [comment]
Also post some details: are you using vim/gvim/nvim , ranger + vim version etc.

**Comment by mauroporras** [comment]
Thanks. Details:

```
➜  ~ nvim --version
NVIM v0.2.0
Build type: Release

➜  ~ ranger --version
ranger-stable 1.8.1
```

**Comment by rafaqz** [comment]
Hah I just realised that your'e not using my plugin, your using francoiscabrol/ranger.vim!

So take the issue up with them, or feel free to swap to this one ;) Its working well for nvim, vim or gvim,  does more things, and will never, ever call sed...
